apiVersion: v1
kind: Service
metadata:
  name: scenario
  namespace: {{ .Values.global.namespace }}
  labels: {{- include "gaia.scenario.selectorLabels" . | nindent 4 }}
spec:
  selector: {{- include "gaia.scenario.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.scenario.service.port }}