server:
  port: ${INGESTION_PORT:8081}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

gaia:
  tick:
    period-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true