server:
  port: ${SCENARIO_PORT:8082}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9093}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:56379}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus