server:
  port: ${SCENARIO_PORT:8282}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:56379}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus