global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "ingestion-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8181"]

  - job_name: "scenario-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8282"]

  - job_name: "ai-service"
    static_configs:
      - targets: ["host.docker.internal:8091"]

  - job_name: "flink"
    static_configs:
      - targets: ["flink-jobmanager:9249", "flink-taskmanager:9249"]